siteUrl: https://esonderegger.github.io/yagss
title: Yagss
description: Yet another generator for static sites
srcDir: docs_src
destDir: docs
templatesDir: docs_templates
scssFile: docs_scss/yagss.scss
